# Generated by Django 3.2 on 2021-04-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210408_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicbook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
