# Generated by Django 3.2 on 2021-04-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comicbook_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comicbook',
            old_name='count_in_stock',
            new_name='stock',
        ),
    ]
