comicbooks = [
    {
        'id': '1',
        'name': "The Infinity Gauntlet",
        'image': "../assets/infinity-gauntlet.jpg",
        'description':
        "The Mad Titan Thanos has seized control of Infinity Gauntlet and with it near-omnipotent power! Who can stop this deadly new overlord? All of Marvel's top heroes star in this epic of cosmic proportions!",
        'creators': "Jim Starlin, George Perez, Ron Lim",
        'publisher': "Marvel",
        'printLength': '241',
        'price': "2,385.38",
        'stock': '20',
        'rating': '4.8',
        'numReviews': '3612',
    },
    {
        'id': '2',
        'name': "The Infinity War",
        'image': "../assets/infinity-war.jpg",
        'description':
        "After Adam Warlock's return in Infinity Gauntlet, his worse half the Magus wasn't far behind! The struggle for ultimate power over the universe continues when a stockpile of evil twins overwhelm the Fantastic Four, Avengers, X-Men, New Warriors, Alpha Flight and more! Will the universe be saved, destroyed... or both?",
        'creators': "Jim Starlin, Ron Lim",
        'publisher': "Marvel",
        'printLength': '400',
        'price': "1,137.53",
        'stock': '20',
        'rating': '4.7',
        'numReviews': '975',
    },
    {
        'id': '3',
        'name': "Secret Wars",
        'image': "../assets/secret-wars.jpg",
        'description':
        "Drawn from Earth across the stars, the Marvel Universe's greatest villains and heroes are set against one another by the mysterious and unbelievably powerful Beyonder, with the winner promised the ultimate prize. But as battle lines are drawn, new alliances forged and old enemies clash, one among them is not willing to settle for anything less than godhood. Can even the combined might of the Avengers, Spider-Man, the Fantastic Four and the X-Men prevent Dr. Doom from becoming the most powerful being in the universe?",
        'creators': "Mike Zeck, Bob Layton, Jim Shooter",
        'publisher': "Marvel",
        'printLength': '376',
        'price': "1,888.52",
        'stock': '20',
        'rating': '4.7',
        'numReviews': '853',
    },
    {
        'id': '4',
        'name': "X-Men Epic Collection: The Fate Of The Phoenix",
        'image': "../assets/x-men-the-fate-of-the-phoenix.jpg",
        'description':
        "Chris Claremont and John Byrne's collaboration ranks among the greatest comic books have ever known. Their X-Men defined Marvel's mutants, but of their many iconic stories, none was more epic or influential than 'The Dark Phoenix Saga.' The X-Men fought many battles, set out on adventures that spanned galaxies and grappled with enemies of limitless might, but nothing could prepare them for their most shocking encounter: One of their own teammates, Jean Grey, has gained power beyond all comprehension, corrupting her and transforming her into the Dark Phoenix! They must fight the woman they cherish or the universe itself will be consumed by her unquenchable fire. Also featuring Wolverine vs. Wendigo, the dystopian debut of 'Days of Future Past' and more!",
        'creators':
        "Chris Claremont, Johny Byrne, Scott Edelman, John Romita, Ken Landgraf, Brent Anderson",
        'publisher': "Marvel",
        'printLength': '480',
        'price': "2,362.56",
        'stock': '10',
        'rating': '4.2',
        'numReviews': '18',
    },
    {
        'id': '5',
        'name': "X-Men",
        'image': "../assets/x-men.jpg",
        'description':
        "X-Men superstars Chris Claremont and Jim Lee bring their legendary run to an Earth-shattering crescendo! The X-Men are shanghaied into outer space to outwit a Skrull infiltration and return Princess Lilandra to the throne - while back home, X-Factor must contend with the return of Apocalypse and the loss of Cyclops' son, Nathan Christopher! Then, both teams unite to face the menace of the Shadow King, leading into an all-new era as the X-Men evolve once again - becoming more than merely Uncanny! And they'll need to be in full fighting form when Magneto gains a cult following, Omega Red returns to menace Wolverine, the time-traveling Bishop joins the team, and the alien Brood assimilate Ghost Rider!",
        'creators':
        "Chris Claremont, Jim Lee, Whilce Portacio, Louise Simonson, Peter David, John Bryne",
        'publisher': "Marvel",
        'printLength': '832',
        'price': "8,559.98",
        'stock': '10',
        'rating': '4.8',
        'numReviews': '67',
    },
    {
        'id': '6',
        'name': "Captain America",
        'image': "../assets/captain-america.jpg",
        'description':
        "Collecting Eisner Award-nominated Best Writer Ed Brubaker's first twenty-five landmark issues of Captain America in one titanic tome, plus the Captain America 65th Anniversary Special and Winter Soldier: Winter Kills one-shots! This deluxe hardcover, fat-packed with extras, features the story that stunned readers worldwide and sent shockwaves through the entire Marvel Universe: the death of Captain America! Also including the return of Cap's wartime partner, Bucky Barnes, as the Winter Soldier; the death and life of his greatest enemy, the Red Skull; and the emergences of a new threat, General Aleksander Lukin, the head of one of the most powerful corporations in the world!",
        'creators':
        "Ed Brubaker, Steve Epting, Michael Lark, Mike Perkins, Lee Weeks",
        'publisher': "Marvel",
        'printLength': '744',
        'price': "5,629.81",
        'stock': '10',
        'rating': '4.9',
        'numReviews': '43',
    },
    {
        'id': '7',
        'name': "Spider-Man: The Complete Collection",
        'image': "../assets/spider-man.jpg",
        'description':
        "Todd McFarlane became a superstar illust'rating' 'AMAZING SP'IDER-MAN, but he changed the industry forever with his next project: the 'adjectiveless' SPIDER-MAN! Taking on both writing and art duties, McFarlane ushered Peter Parker into a gritty new era - and it began with 'Torment'! When the Big Apple's streets run red with blood, the web-slinger heads into the sewers to stop the Lizard's homicidal rampage. But what is driving his old friend and foe? Plus: Ghost Rider lends a bony hand when the deranged Hobgoblin returns, the wall-crawler finds himself at the center of a clash of claws between Wolverine and Wendigo, and Pete goes back in black to face Morbius the Living Vampire! And in the ultimate nineties team-up, Spidey joins X-Force to battle the unstoppable Juggernaut!",
        'creators': "Todd McFarlane, Rob Liefeld, Fabian Nicieza",
        'publisher': "Marvel",
        'printLength': '440',
        'price': "2,462.23",
        'stock': '10',
        'rating': '3.9',
        'numReviews': '22',
    },
    {
        'id': '8',
        'name': "Deadpool Kills the Marvel Universe",
        'image': "../assets/deadpool-kills-the-marvel-universe.jpg",
        'description':
        "Deadpool Kills the Marvel Universe: What if everthing you thought was funny about Deadpool...was actually just disturbing? What if he decided to kill everyone and everything that makes up the Marvel Universe? What if he actually pulled it off? Would that be FUN for you? The Merc with a Mouth takes a turn for the twisted in a weekly horror comic like no other...",
        'creators': "Cullen Bunn, Dalibor Talajic",
        'publisher': "Marvel",
        'printLength': '188',
        'price': "2,999.42",
        'stock': '0',
        'rating': '4.5',
        'numReviews': '2625',
    },
    {
        'id': '9',
        'name': "Doctor Doom, Vol.2",
        'image': "../assets/doctor-doom.jpg",
        'description':
        "After uncovering the Symkarian plot against him, Doctor Doom seeks an 'insurance policy' that will ensure his reign over Latveria -forever! But before Doom returns to his homeland to wage a one-man war on those who usurped his throne, he must embark on a covert mission to find a secret and powerful device -with an unlikely ally, Kang the Conqueror -while being pursued by mercenaries hired to kill him on sight! Meanwhile, the black hole on the moon is growing critical, and Doom's brilliant mind may be the only thing that can stop a catastrophe that will wreak havoc through the entire solar system. Still, Victor isn't one to just offer a friendly hand. If the people of Earth want his help, he's going to make them beg for it...",
        'creators': "Christopher Cantwell, Salvador Larroca",
        'publisher': "Marvel",
        'printLength': '112',
        'price': "1,171.01",
        'stock': '2',
        'rating': '4.1',
        'numReviews': '8',
    },
    {
        'id': '10',
        'name': "DC Comics Encyclopedia: All-New Edition",
        'image': "../assets/dc-comics-encyclopedia.jpg",
        'description':
        "Revamped, redesigned, and fully updated to include the New 52 and Rebirth storylines, this is the definitive and indispensable guide to the characters and worlds of the DC Comics Universe. Created in full collaboration with DC Comics, this comprehensive reference book has The Washington Post saying, 'The DC Comics Encyclopedia is a must.' Formatted in an easy-to use A-to-Z layout, this guide is packed with information and thrilling comic book art and features more than 1,100 characters including Batman, Superman, Wonder Woman, The Joker, and much more. The DC Comics Encyclopedia All-New Edition brings everything up to date, providing an accessible, compelling, and lavishly illustrated guide to the dynamics of the DC Comics Universe.",
        'creators': "Matthew K. Manning, Alex Irvine",
        'publisher': "DC Comics",
        'printLength': '368',
        'price': "1,338.40",
        'stock': '10',
        'rating': '4.9',
        'numReviews': '2327',
    },
    {
        'id': '11',
        'name': "Flashpoint",
        'image': "../assets/flashpoint.jpg",
        'description':
        "Not a dream, not an imaginary story, not an elseworld. This is Flash Fact: When Barry Allen wakes at his desk, he discovers the world has changed. Family is alive, loved ones are strangers, and close friends are different, gone or worse. It's a world on the brink of a cataclysmic war—but where are Earth's Greatest Heroes to stop it? It's a place where America's last hope is Cyborg, who hopes to gather the forces of The Outsider, The Secret 7, Shazam!, Citizen Cold and other new and familiar-yetaltered faces! It's a world that could be running out of time, if The Flash can't find the villain who altered the time line!",
        'creators': "Geoff Johns",
        'publisher': "DC Comics",
        'printLength': '176',
        'price': "9,765.23",
        'stock': '15',
        'rating': '4.8',
        'numReviews': '1725',
    },
    {
        'id': '12',
        'name': "Injustice: The Complete Collection",
        'image': "../assets/injustice.jpg",
        'description':
        "Forget everything you think you know about the DC Universe. Tradition is tossed aside and chaos erupts in Injustice: Gods Among Us Year One—The Complete Edition, inspired by the video game phenomenon! This graphic novel edition collects the initial year of the best-selling series in its entirety for the first time! Superman is Earth’s greatest hero. But when the Man of Steel can’t protect the thing he holds most dear, he decides to stop trying to save the world—and start ruling it. Now, the Last Son of Krypton is enforcing peace on Earth by any means necessary. Only one man stands between Superman and absolute power: Batman. And the Dark Knight will use any method at his disposal to stop his former friend from reshaping the world in his shattered 'image'.",
        'creators': "Tom Taylor, Jheremy Raapack, Mike S.Miller",
        'publisher': "DC Comics",
        'printLength': '424',
        'price': "1,220.46",
        'stock': '10',
        'rating': '4.8',
        'numReviews': '1054',
    },
    {
        'id': '13',
        'name': "The Flash: Rebirth",
        'image': "../assets/the-flash-rebirth.jpg",
        'description':
        "The epic story of Barry Allen’s return from the dead to reclaim his title as The Fastest Man Alive is collected in hardcover. Geoff Johns and Ethan Van Sciver, the writer/artist team behind the blockbuster Green Lantern: Rebirth and The Sinestro Corps War, create an explosive, jaw-dropping epic that reintroduces Barry Allen, the modern–age Flash. But how will Barry Allen find his place in the twenty-first century?",
        'creators': "Geoff Johns, Ethan van Sciver",
        'publisher': "DC Comics",
        'printLength': '168',
        'price': "860.24",
        'stock': '10',
        'rating': '4.7',
        'numReviews': '575',
    },
    {
        'id': '14',
        'name': "Transformers Classics, Vol. 1",
        'image': "../assets/transformers-classics.jpg",
        'description':
        "The original series faithfully reproduced after 25 years! After saving their own world from a celestial catastrophe, the Autobots and Decepticons have crashed landed on Earth! Each side sets out to explore their new surroundings, seeking resources and possibly allies. One such ally may be a bookworm 'name'd Buster Witwicky, and his mechanic father, Sparkplug.",
        'creators': "Bill Mantlo, Ralph Macchio, Jim Salicrup, Bob Budiansky",
        'publisher': "IDW Publishing",
        'printLength': '318',
        'price': "912.30",
        'stock': '9',
        'rating': '4.7',
        'numReviews': '123',
    },
    {
        'id': '15',
        'name': "Transformers: Unicron",
        'image': "../assets/transformers-unicron.jpg",
        'description':
        "The end is nigh! Unicron, a planet-sized being that devours other worlds, has set its sights on Cybertron and all of its colonies--including Earth! Optimus Prime, Bumblebee, and their friends must unite every Cybertronian, Earthling, and ally they have to stand against this threat to all existence. But why is Unicron hell-bent on destroying Cybertron? What original sin did Optimus Prime's ancestors commit to earn this wrath? It's an all-out battle against extinction as the world-destroying, universe-shattering threat of Unicron comes to end everything.",
        'creators': "John Barber, Alex Milne, Sara Pitre-Durocher, Andrew Griffith",
        'publisher': "IDW Publishing",
        'printLength': '232',
        'price': "841.98",
        'stock': '5',
        'rating': '4.6',
        'numReviews': '95',
    },
    {
        'id': '16',
        'name': "Transformers Prime: Beast Hunters, Vol. 1",
        'image': "../assets/transformers-prime-beast-hunters.jpg",
        'description':
        "It's the beginning of the end for Transformers Prime! But a new enemy is revealed and the stakes are racheted up even higher as the Cybertronians continue their quest for peace throughout the universe.",
        'creators': "Mike Johnson",
        'publisher': "IDW Publishing",
        'printLength': '112',
        'price': "1064.48",
        'stock': '3',
        'rating': '4.6',
        'numReviews': '13',
    },
]
