export const COMICBOOK_LIST_REQUEST = "COMICBOOK_LIST_REQUEST";
export const COMICBOOK_LIST_SUCCESSFUL = "COMICBOOK_LIST_SUCCESSFUL";
export const COMICBOOK_LIST_FAILED = "COMICBOOK_LIST_FAILED";

export const COMICBOOK_ITEM_REQUEST = "COMICBOOK_ITEM_REQUEST";
export const COMICBOOK_ITEM_SUCCESSFUL = "COMICBOOK_ITEM_SUCCESSFUL";
export const COMICBOOK_ITEM_FAILED = "COMICBOOK_ITEM_FAILED";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
