export const COMICBOOK_LIST_REQUEST = "COMICBOOK_LIST_REQUEST";
export const COMICBOOK_LIST_SUCCESSFUL = "COMICBOOK_LIST_SUCCESSFUL";
export const COMICBOOK_LIST_FAILED = "COMICBOOK_LIST_FAILED";

export const COMICBOOK_ITEM_REQUEST = "COMICBOOK_ITEM_REQUEST";
export const COMICBOOK_ITEM_SUCCESSFUL = "COMICBOOK_ITEM_SUCCESSFUL";
export const COMICBOOK_ITEM_FAILED = "COMICBOOK_ITEM_FAILED";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
